version: '3.4'

volumes:
  pgdata:

services:
    my_awesome_list:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4001:${PORT}"
        depends_on:
            - db

    db:
        image: postgres:latest
        env_file: 
            - .env
        ports:
            - '${POSTGRES_PORT}:5432'

        volumes:
            - pgdata:/var/lib/postgresql/data
